// model/AuditAction.java
package ac.muast.it.asset_registry.model;

public enum AuditAction {
    CREATED,
    UPDATED,
    DELETED,
    ASSIGNED,
    TRANSFERRED,
    CHECKED_IN,
    SENT_FOR_REPAIR,
    RETURNED_FROM_REPAIR,
    LOST,
    DECOMMISSIONED,
    RECOVERED,
    LOANED,
    RETURNED_FROM_LOAN,
    STOCK_RECEIVED,
    STOCK_TRANSFERRED,
    STOCK_ADJUSTED,
    STOCK_CONSUMED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PERMISSIONS_CHANGED;
}